### ISSUE TITLE
Open ports with iptables

### ISSUE THREAD

**Issue by bkane-msft** [bbkane/shovel_ansible#2]
The shell:

```bash
sudo iptables -A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
sudo iptables -A INPUT -p tcp -m tcp --dport 5080 -j ACCEPT
```

Ansible example from https://docs.ansible.com/ansible/latest/collections/ansible/builtin/iptables_module.html 

```yaml
- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "8081:8083"
    jump: ACCEPT
```

Saving the in-memory iptables update with shell:

```bash
sudo iptables-save | sudo tee /etc/systemd/scripts/ip4save
sudo systemctl restart iptables
```

Need to figure out how to do that in Ansible
